baseURL = "https://ngosangns.com/"
title = "ngosangns"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ngosangns"
description = "Welcome to my blog"
keywords = [ "ngosangns", "blog" ]
author = "ngosangns"
images = [ "https://avatars.githubusercontent.com/u/46277436" ]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "https://avatars.githubusercontent.com/u/46277436"
favicon16x16 = "https://avatars.githubusercontent.com/u/46277436"
favicon32x32 = "https://avatars.githubusercontent.com/u/46277436"
apple_touch_icon = "https://avatars.githubusercontent.com/u/46277436"
safari_pinned_tab = "https://avatars.githubusercontent.com/u/46277436"

[params.label]
text = "ngosangns"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ngosangns"
subtitle = "Software developer"
imageUrl = "https://avatars.githubusercontent.com/u/46277436"
imageWidth = 120
imageHeight = 120
imageTitle = "ngosangns"

# [[params.profileMode.buttons]]
# name = "Posts"
# url = "/blog/posts"

# [[params.profileMode.buttons]]
# name = "Tags"
# url = "/tags"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog"

# [[params.socialIcons]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/ngosangns"

# [[params.socialIcons]]
# name = "github"
# url = "https://github.com/ngosangns"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

# [params.editPost]
# URL = "https://github.com/<path_to_repo>/content"
# Text = "Suggest Changes"
# appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "about-me"
name = "About me"
url = "/about-me/"
weight = 10

[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
hardWraps = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]